spring.application.name=minigarden

# SERVER
server.port=8080

# DATABASE (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/minigarden?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# CORS (cho React Vite)
spring.web.cors.allowed-origins=http://localhost:5173
spring.web.cors.allowed-methods=*
spring.web.cors.allowed-headers=*

# ENCODING (tránh lỗi tiếng Việt)
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# CLOUD
cloudinary.cloud-name=do1rmzt7f
cloudinary.api-key=619846771428842
cloudinary.api-secret=KLF0gB3krf3L0Ajck5uYUPFW5DU

# MAIL CONFIG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vongoclinh.l2019@gmail.com
spring.mail.password=mgub bnje gtbb qzgi

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# GOOGLE OAUTH2
spring.security.oauth2.client.registration.google.client-id=Google-Client-ID
spring.security.oauth2.client.registration.google.client-secret=Google-Client-Secret

spring.security.oauth2.client.registration.google.scope=email,profile

# redirect mặc định (Spring tự xử lý)
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

# Gemini API Configuration
gemini.api.key=AIzaSyD5fxLeYBL2ML6pDlZNZcvEagSnT2Lqo_U
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

#Config GHN
ghn.token=c0adb3f6-0fcd-11f0-b2fa-667dc40812a3
ghn.shop-id=5715666
#district thủ đức
ghn.from-district-id=3695 
#ward phường linh trung
ghn.from-ward-code=90737
